name: 'Publish package'
description: 'Publishes packages to aws'
inputs:
  DOCKER_USERNAME:
    required: true
  DOCKER_PASSWORD:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: "Deploy Snapshot"
      env:
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        ./mvnw $MAVEN_CLI_OPTS $MAVEN_OPTS deploy

    - name: "Deploy Release"
      env:
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        ./mvnw $MAVEN_CLI_OPTS $MAVEN_OPTS release:perform

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.DOCKER_USERNAME }}
        password: ${{ inputs.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true