name: Deploy product

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        shell: bash
        env:
          GH_USERNAME: ${{ vars.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          ./mvnw -s .m2/settings.xml clean install -pl fastfood-product -Dmaven.test.skip=true -U -P dev

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: icarodamiani/fastfood-product:latest
          push: true

      - name: Deploy Helm
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.9
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-east-1"
          cluster-name: "eks-cluster-fastfood-t4-g86"
          config-files: charts/fastfood-product/values.yaml
          chart-path: charts/
          namespace: default
          name: fastfood-product
          values: mongo_host=fastfood-documentdb.cluster-cdsw6i8u48rd.us-east-1.docdb.amazonaws.com,mongo_password= ${{ inputs.MONGO_PASSWORD }}