name: Deploy product

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/run-deploy
        with:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          CLUSTER_NAME: "eks-cluster-fastfood-t4-g86"
          VALUES_PATH: charts/fastfood-product/values.yaml
          RELEASE_NAME: fastfood-product
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
