name: Deploy product

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    environment:
      name: dev
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true

      - name: Deploy Helm
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.9
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-east-1"
          cluster-name: "eks-cluster-fastfood-t4-g86"
          config-files: charts/fastfood-product/values.yaml
          chart-path: charts/
          namespace: default
          name: fastfood-product
          values: mongo_host=fastfood-documentdb.cluster-cdsw6i8u48rd.us-east-1.docdb.amazonaws.com,mongo_password= ${{ inputs.MONGO_PASSWORD }}