name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "development" ]
  workflow_call:

  workflow_dispatch:

env:
  CLUSTER_NAME: "eks-cluster-fastfood-t4-g86"

jobs:
  build:
    environment:
      name: dev
    runs-on: ubuntu-latest
    container:
      image: openjdk:17.0.1-jdk-slim
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/run-build
        with:
          GH_USERNAME: ${{vars.GH_USERNAME}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}

  publish:
    environment:
      name: dev
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/run-publish
        with:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    environment:
      name: dev
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/run-deploy
        with:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          CLUSTER_NAME: ${{ env.CLUSTER_NAME }}
          VALUES_PATH: charts/fastfood-product/values.yaml
          RELEASE_NAME: fastfood-product
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}